server:
  port: 80
  servlet:
    context-path: /order


spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://120.79.41.56:3306/demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1328174
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


