server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
  # zk默认使用是主机名称作为注册地址,如果主机名称解析错误,可以配置ip
#    inetutils:
#      default-hostname: localhost
    zookeeper:
      connect-string: 120.79.41.56:2181
#      discovery:
#        instance-host: ${spring.cloud.inetutils.default-hostname}
