server:
  port: 8001
  servlet:
    context-path: /payment



spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://120.79.41.56:3306/demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1328174
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    fetch-registry: true  # true 表示检索注册信息
    register-with-eureka: true  # true 表示将自己注册到eureka中
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka  # 单机版

#      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka # 集群版

  instance:
    instance-id: payment8001 #主机名称的指定,不然就用默认的
    prefer-ip-address: true
    # eureka客户端向服务端发送心跳的时间间隔(默认30s)
#    lease-renewal-interval-in-seconds: 1
#    # eureka服务端在收到客户端最后一次心跳后的等待时间上限(默认90s),超时将中踢除服务
#    lease-expiration-duration-in-seconds: 2

