server:
  port: 9527



spring:
  application:
    name: cloud-gateway
  cloud:  # gateway配置网关的第一种方式 (第二种方式通过代码配置)
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:     # http://127.0.0.1:8001/payment/findById/5(直接访问)  ---> http://127.0.0.1:9527/payment/findById/5(走网关访问)
        - id: payment-routh             # 路由id, 可以随便机,但需要唯一
#          uri: http://localhost:8001    # 匹配提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   # 开启discovery后,就可以通过微服务名进行路由
          predicates:
            - Path=/payment/findById/**   # 断言 路径相匹配的才进行路由
#            - Cookie=username, admin      # cooKie中包含"username=admin"
#            - Method=GET

        - id: payment-routh1             # 路由id, 可以随便机,但需要唯一
#          uri: http://localhost:8001    # 匹配提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/feign/**   # 断言 路径相匹配的才进行路由
#            - After=2020-04-19T23:43:50.514+08:00[Asia/Shanghai]  # 表示在此时间之后的请求才生效
#            - Cookie=username, admin
eureka:
  client:
    fetch-registry: true  # true 表示检索注册信息
    register-with-eureka: true  # true 表示将自己注册到eureka中
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka  # 单机版

